name: CI

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (Frontend)
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Install dependencies (Backend)
        run: |
          cd backend
          npm install

      - name: Start Backend
        run: |
          cd backend
          npm start

      - name: Start Frontend
        run: |
          cd frontend
          npm start
